## Playbook to clone private Github repos
# Password is not stored on disk 
# Input:  
#   repo_path: repo path like https://github.com/username/repo.git
#   repo_dest: dest folder. 
#   as_root: yes/no
- name: Git private repo clone
  hosts: console
#  vars_prompt: 
#    - name: "githubuser" 
#      prompt: "Enter your github username" 
#      private: no 
#    - name: "githubpassword" 
#      prompt: "Enter your github password" 
#      private: yes 

  tasks:
    - name: get username
      pause:
        prompt: 'Enter pass'
        echo: no
      register: userpassword

    - name: 'Create foler {{repo_dest}} if does not exist'
      file:
        path: '{{repo_dest}}'
        state: directory
      become: '{{as_root | bool}}'

    - debug:
        msg: 'Cloning {{repo_path}} into {{repo_dest}}'

    - set_fact:
        modified_repo: '{{repo_path.split("://")[0]}}://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@{{repo_path.split("://")[1]}}' 

    - debug:
        msg: '{{modified_repo}}'

    - git:
        repo: '{{modified_repo}}'
        dest: '{{repo_dest}}'
      become: '{{as_root | bool}}'
      no_log: false
