#
# Modify all passwords
# # First modify super user password itself
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{postgres.default_password}}' 
    username: '{{postgres.user}}' 
    new_passwd: '{{secrets.postgres.su}}' 

# sysadmin
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: 'sysadmin'
    new_passwd: '{{secrets.postgres.sysadmin}}' 

# dbadmin
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: 'dbadmin'
    new_passwd: '{{secrets.postgres.dbadmin}}' 

# appadmin
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: 'appadmin'
    new_passwd: '{{secrets.postgres.appadmin}}' 

# kernel
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_kernel.user}}' 
    new_passwd: '{{secrets.postgres.kerneluser}}' 

# master
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_master.user}}' 
    new_passwd: '{{secrets.postgres.masteruser}}' 

# regprc
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_regprc.user}}' 
    new_passwd: '{{secrets.postgres.regprcuser}}' 

# prereg
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_prereg.user}}' 
    new_passwd: '{{secrets.postgres.prereguser}}' 

# ida
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_ida.user}}' 
    new_passwd: '{{secrets.postgres.idauser}}' 

# idrepo
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_idrepo.user}}' 
    new_passwd: '{{secrets.postgres.idrepouser}}' 

# pmp
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_pmp.user}}' 
    new_passwd: '{{secrets.postgres.pmpuser}}' 

# audit
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_audit.user}}' 
    new_passwd: '{{secrets.postgres.audituser}}' 

# idmap
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_idmap.user}}' 
    new_passwd: '{{secrets.postgres.idmapuser}}' 

# iam
- import_tasks: 'db_passwd.yml'
  vars:
    su_password: '{{secrets.postgres.su}}'   # new password changed in above step
    username: '{{databases.mosip_iam.user}}' 
    new_passwd: '{{secrets.postgres.iamuser}}' 

