# Master playbook
# Notes:
# - Taints are applied only after monitoring tools have been installed on the pods.

# Console
- import_playbook: playbooks/console.yml  # Basic setup on console machine
- name : Finished Console.yml
  shell: /bin/echo "FINISHED CONSOLE.yml"
- import_playbook: playbooks/coredns.yml
- name : Finished COREDNS.yml
  shell: /bin/echo "FINISHED COREDNS.yml"
- import_playbook: playbooks/nginx.yml # Setting nginx in advance so that Keycloak etc. can be tested 
- name : Finished NGINX.yml
  shell: /bin/echo "FINISHED NGINX.yml"
- import_playbook: playbooks/nfs.yml 
- name : Finished NFS.yml
  shell: /bin/echo "FINISHED NFS.yml"
# MZ cluster
- import_playbook: playbooks/mzcluster.yml
- name : Finished mzcluster.yml
  shell: /bin/echo "FINISHED mzcluster.yml"
- import_playbook: playbooks/mz-nfs-provisioner.yml
- name : Finished mz-nfs-provisioner.yml
  shell: /bin/echo "FINISHED mz-nfs-provisioner.yml"
- import_playbook: playbooks/mzmonitoring.yml
- name : Finished mzmonitoring.yml
  shell: /bin/echo "FINISHED mzmontoring.yml"
- import_playbook: playbooks/taints.yml # At this point we apply any taints for MOSIP pods. 
- name : Finished taints.yml
  shell: /bin/echo "FINISHED taints.yml"
# DMZ cluster
- import_playbook: playbooks/dmzcluster.yml
- name : Finished dmzcluster.yml
  shell: /bin/echo "FINISHED dmzcluster.yml"
- import_playbook: playbooks/dmz-nfs-provisioner.yml
- name : Finished dmz-nfs-provisioner.yml
  shell: /bin/echo "FINISHED dmz-nfs-provisioner.yml"
- import_playbook: playbooks/dmzmonitoring.yml
- name : Finished dmzmonitoring.yml
  shell: /bin/echo "FINISHED dmzmonitoring.yml"
# Non-MOSIP modules
- import_playbook: playbooks/postgres.yml
- name : Finished postgres.yml
  shell: /bin/echo "FINISHED postgres.yml"
- import_playbook: playbooks/keycloak.yml
- name : Finished keycloak.yml
  shell: /bin/echo "FINISHED keycloak.yml"
- import_playbook: playbooks/mzclamav.yml  # Each zone has it's own clamav
- name : Finished mzclamav.yml
  shell: /bin/echo "FINISHED mzclamav.yml"
- import_playbook: playbooks/dmzclamav.yml
- name : Finished dmzclamav.yml
  shell: /bin/echo "FINISHED dmzclamav.yml"
- import_playbook: playbooks/activemq.yml
- name : Finished activemq.yml
  shell: /bin/echo "FINISHED activemq.yml"
#- import_playbook: playbooks/mock-biosdk.yml    #TODO
- import_playbook: playbooks/minio.yml
- name : Finished minio.yml
  shell: /bin/echo "FINISHED minio.yml"
- import_playbook: playbooks/artifactory.yml
- name : Finished artifactory.yml
  shell: /bin/echo "FINISHED artifactory.yml"
# MOSIP modules
- import_playbook: playbooks/config-server.yml
- name : Finished config-server.yml
  shell: /bin/echo "FINISHED config-server.yml"
- import_playbook: playbooks/kernel.yml
- name : Finished kernel.yml
  shell: /bin/echo "FINISHED kernel.yml"
- import_playbook: playbooks/packetmanager.yml
- name : Finished packetmanager.yml
  shell: /bin/echo "FINISHED packetmanager.yml"
- import_playbook: playbooks/datashare.yml
- name : Finished datashare.yml
  shell: /bin/echo "FINISHED datashare.yml"
- import_playbook: playbooks/prereg.yml
- name : Finished prereg.yml
  shell: /bin/echo "FINISHED prereg.yml"
- import_playbook: playbooks/websub.yml
- name : Finished websub.yml
  shell: /bin/echo "FINISHED websub.yml"
- import_playbook: playbooks/regproc.yml
- name : Finished regproc.yml
  shell: /bin/echo "FINISHED regproc.yml"
- import_playbook: playbooks/ida.yml
- name : Finished ida.yml
  shell: /bin/echo "FINISHED ida.yml"
- import_playbook: playbooks/idrepo.yml
- name : Finished idrepo.yml
  shell: /bin/echo "FINISHED idrepo.yml"
- import_playbook: playbooks/pms.yml
- name : Finished pms.yml
  shell: /bin/echo "FINISHED pms.yml"
- import_playbook: playbooks/resident.yml
- name : Finished resident.yml
  shell: /bin/echo "FINISHED resident.yml"
- import_playbook: playbooks/admin.yml
- name : Finished admin.yml
  shell: /bin/echo "FINISHED admin.yml"
- import_playbook: playbooks/print.yml
- name : Finished print.yml
  shell: /bin/echo "FINISHED print.yml"
- import_playbook: playbooks/mockabis.yml
- name : Finished mockabis.yml
  shell: /bin/echo "FINISHED mockabis.yml"
# Regclient downloader
- import_playbook: playbooks/reg-client-downloader.yml
- name : Finished reg-client-downloader.yml
  shell: /bin/echo "FINISHED reg-client-downloader.yml"
