# letsencrypt requires latest version of various python modules, hence
# We will run in a virtual environment of python3
- name: Install virtualenv
  yum:
    name: python-virtualenv 
    state: present
  become: yes


#alter below since new cryptography releases have rust dependency that throws an error.
- name: Install certbot in python3 virtual environment 
  pip:
    name: 
      - cryptography==3.3.2
      - 'certbot=={{certbot_version}}'
    virtualenv_python: python3
    virtualenv: '{{ansible_env.HOME}}/.venv-py3'
    state: present

- name: Install certbot-nginx
  pip:
    name: 
      - cryptography==3.3.2
      - 'certbot-nginx=={{certbot_nginx_version}}'
    virtualenv: '{{ansible_env.HOME}}/.venv-py3'
    state: present

- name: run certbot 
  command: '{{ansible_env.HOME}}/.venv-py3/bin/certbot certonly --nginx -n  -m "{{ssl.ca.letsencrypt.email}}" --agree-tos -d "{{sandbox_domain_name}}"'
  become: yes
  register: out

- debug:
    msg: '{{out}}'

